#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = WebBrowser
APP_NAME = WebBrowser
WebBrowser_APPLICATION_ICON = WebBrowser.tiff


#
# Resource files
#
WebBrowser_RESOURCE_FILES = \
Resources/WebBrowser.gorm \
Resources/Document.gorm \
Resources/Preferences.gorm \
Resources/FindPanel.gorm \
Resources/DownloadPanel.gorm \
Resources/LinkPanel.gorm \
Resources/Home.tiff \
Resources/Left.tiff \
Resources/Right.tiff \
Resources/WebBrowser.tiff \
Resources/url.tiff \
Resources/html.tiff \
Resources/webview \
Resources/ApplicationScripting.xlp \
Resources/ScriptingInfo.plist 


#
# Header files
#
WebBrowser_HEADER_FILES = \
AppController.h \
Document.h \
Preferences.h \
common.h \
XEmbeddedView.h \
xembed.h \
ChromeWebView.h \
ExternalWebView.h \
ChromeController.h \
FindPanel.h \
DownloadPanel.h \
LinkPanel.h \
BrowserWindow.h \
BrowserApp.h \
LocalFileServer.h \
LinkIcon.h \
STScriptingSupport.h

#
# Objective-C Class files
#
WebBrowser_OBJC_FILES = \
AppController.m \
Document.m \
Preferences.m \
common.m \
XEmbeddedView.m \
ChromeWebView.m \
ExternalWebView.m \
ChromeController.m \
FindPanel.m \
DownloadPanel.m \
LinkPanel.m \
BrowserWindow.m \
BrowserApp.m \
LocalFileServer.m \
LinkIcon.m \
Document+scripting.m \
STScriptingSupport.m \
AppController+scripting.m

#
# Other sources
#
WebBrowser_C_FILES = \
xembed.c 

WebBrowser_OBJC_FILES += \
WebBrowser_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
